spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/csv_lines
    username: root
#  h2:
#    console:
#      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: auditevents,beans,conditions,configprops,env,flyway,health,heapdump,httptrace,info,jolokia,logfile,loggers,metrics,mappings,scheduledtasks,threaddump
      base-path: /ops
    enabled-by-default: true
logging:
  level:
    io:
      corbs:
        csvkit: DEBUG